<#
.SYNOPSIS
    Step 20 - Start the move requests (manual completion mode).

.DESCRIPTION
    How it works:
        - Reads MigrationPlan.csv generated by step 19.
        - Removes all existing MoveRequests before submitting.
        - Assigns a TargetDatabase to each MoveRequest, round-robin over the
          available Exchange 2019 databases.
        - New-MoveRequest with -SuspendWhenReadyToComplete: the synchronization
          runs but the completion must be triggered manually (Step21).
        - Generates MigrationStatus.html at the end of the Apply.

    Follow mode (FOLLOW):
        - Set $env:FOLLOW = '1' before running to enter follow mode.
        - In this mode, no migration action is performed.
        - An HTML report MigrationStatus.html is generated with the current state
          of all MoveRequests, by batch and by mailbox.
        - Can be used in Inventory or Apply mode alike.

    Re-run in Apply mode:
        - All existing MoveRequests are removed before the re-submission
          (clean slate, including the Completed MRs from previous steps).
        - Idempotent: running it several times gives the same final result.

    v1.4 - Single-batch focus mode (triggered by Step21 -FollowAfter -BatchNumber NN):
        - Read via $Global:FollowBatchFilter = 'BatchNN' set by the orchestrator.
        - Get-OfficialMigrationBatches: restricted to a single batch via
          Get-MigrationBatch -Identity BatchNN (server-side filter).
        - Get-MbSnapshot: Get-MoveRequest -BatchName 'MigrationService:BatchNN'
          instead of a full Get-MoveRequest + client-side filter (about 10x faster
          on 455 MRs).
        - The generated HTML uses a dedicated name: MigrationStatus-BatchNN.html
          (allows 2 FOLLOW sessions in parallel - global + focus - without collision).
        - The HTML title explicitly mentions "(focus)".

    v1.4 - Quarantined UI / Synced palette:
        - New dimension orthogonal to Status: MoveRequestStatistics.StatusDetail
          (StalledDueToMRS_Quarantined, StalledDueToTarget_*) - a 'Synced' user can
          be quarantined on the MRS side. Shown as an orange sub-badge + clickable
          tile + batch pill + action banner.
        - Synced palette: changed from orange (#c07600) to purple (#6d28d9) so that it
          is no longer confused with the orange Quarantined (close to the error red).
        - Per-batch display: 'average sync %' (average of the user-level
          PercentageComplete) AND '% finalized' shown separately - useful when the
          batch is globally at 95% sync but 0% finalized.

.NOTES
    Author  : Nicolas Fabert
    Version : 2.0.0
    Part of : Exchange 2013/2016 to 2019 Migration - Deploy-Exchange2019.ps1
#>

function Invoke-Step {
    [CmdletBinding()]
    param(
        [string]$Mode,
        [string]$OutputFolder,
        [string]$CsvFolder,
        [hashtable]$Config,
        [System.Management.Automation.PSCredential]$Credential
    )

    # =========================================================================
    # Helper: HTML migration status report
    # =========================================================================
    function New-MigrationStatusHtml {
        # v1.3+: batch-centric report based on Get-MigrationBatch
        # Stats = array of PSCustomObject (see Get-MbSnapshot)
        #   { Name, Status, TotalCount, ActiveCount, SyncedCount, FinalizedCount,
        #     FailedCount, StoppedCount, CreatedDate, CompleteAfter, Users[] }
        param(
            [object[]]$Stats,
            [string]$OutputPath,
            [string]$ReportMode,
            [string]$Title = 'Exchange 2019 migration status',
            # If > 0: adds a browser meta refresh (used by FOLLOW mode).
            [int]$AutoRefreshSeconds = 0
        )

        function Esc {
            param([string]$s)
            if ([string]::IsNullOrEmpty($s)) { return '' }
            $s -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
        }

        # Colors per status (aligned with Exchange: MigrationBatch + MigrationUser)
        # MigrationBatch.Status : Created, Syncing, Synced, Completing, Completed, Failed, Stopped, CompletedWithErrors
        # MigrationUser.Status  : Provisioning, Provisioned, Stopped, Synced, Failed, IncrementalSync, Syncing, Completed, Active
        $clr = @{
            # Green: everything is completed
            'Completed'='var(--cp-success)'; 'CompletedWithErrors'='var(--cp-teal)'
            # Blue: in progress
            'Syncing'='var(--cp-info)'; 'IncrementalSync'='var(--cp-info)'; 'Active'='var(--cp-info)'
            'Provisioning'='var(--cp-info)'; 'Provisioned'='var(--cp-info)'; 'Created'='var(--cp-text-muted)'
            # Orange: waiting for manual completion
            'Synced'='var(--cp-violet)'; 'Completing'='var(--cp-violet)'
            # Red: failure / stopped
            'Failed'='var(--cp-danger)'; 'Stopped'='var(--cp-danger)'
            'default'='var(--cp-text-muted)'
        }
        # Indicators for the display priority (Failed on top, Completed at the bottom)
        $statusSort = @{
            'Failed'=1; 'Stopped'=2
            'Synced'=3; 'Completing'=4
            'Active'=5; 'Syncing'=5; 'IncrementalSync'=5
            'Provisioning'=6; 'Provisioned'=6; 'Created'=7
            'Completed'=8; 'CompletedWithErrors'=8
        }

        $now    = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        $stamp  = Get-Date -Format 'yyyyMMdd_HHmmss'
        $nbBatch = if ($Stats) { @($Stats).Count } else { 0 }

        # Mapping user status -> displayed group (tile)
        # batch.SyncedCount / FinalizedCount does NOT always reflect the user-level state
        # (Exchange only increments batch.SyncedCount at the batch.Status=Synced transition).
        # So we aggregate from Users[].Status to get exact counters.
        $grpFinal   = @('Completed','CompletedWithErrors')
        $grpSynced  = @('Synced')
        $grpActive  = @('Syncing','IncrementalSync','Active','Provisioning','Provisioned','Created')
        $grpFailed  = @('Failed','Stopped')

        # Quarantined filter: MRS poisoned the move (StalledDueToMRS_*, StalledDueToTarget_*).
        # Criterion: StatusDetail starts with 'Stalled' or contains 'Quarantine'.
        # This predicate is orthogonal to Status (a 'Synced' user can be Quarantined).
        # NB: inline test rather than a shared scriptblock to avoid the
        # 'Cannot overwrite variable u' collision (PS 5.1 optimization scope) with the foreach.

        $allUsers     = @($Stats | ForEach-Object { $_.Users })
        $totalMbx     = @($allUsers).Count
        $totalFinal   = @($allUsers | Where-Object { $_.Status -in $grpFinal  }).Count
        $totalSynced  = @($allUsers | Where-Object { $_.Status -in $grpSynced }).Count
        $totalActive  = @($allUsers | Where-Object { $_.Status -in $grpActive }).Count
        $totalFailed  = @($allUsers | Where-Object { $_.Status -in $grpFailed }).Count
        $totalQuar    = @($allUsers | Where-Object { $_.StatusDetail -and ([string]$_.StatusDetail -match '^Stalled|Quarantine') }).Count
        # Average global progress (user-level PercentageComplete aggregated)
        $globalAvgPct = if ($totalMbx -gt 0) {
            [math]::Round((($allUsers | Measure-Object -Property PercentageComplete -Sum).Sum) / $totalMbx)
        } else { 0 }
        $globalPct = if ($totalMbx -gt 0) { [math]::Round($totalFinal * 100 / $totalMbx) } else { 0 }

        $sb = [System.Text.StringBuilder]::new(250000)

        # ---- HEAD: shared report theme of the module + classes of this report ----
        $extraStyle = @"
.leg{position:relative;display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;font-size:12px;color:var(--cp-text-muted);align-items:center}
.leg-sq{display:inline-block;width:11px;height:11px;border-radius:3px;margin-right:5px;vertical-align:middle}
.acc-step{flex:0 0 auto;min-width:80px}.acc-bar{flex:1;min-width:140px;max-width:260px}
.acc-pct{font-size:12px;font-weight:600;white-space:nowrap;color:var(--cp-text-muted)}.acc-pills{margin-left:auto}
.td-dn{font-weight:600}.td-al{font-size:12px;color:var(--cp-text-muted)}
.mbar{display:flex;height:8px;border-radius:8px;overflow:hidden;background:var(--cp-border);min-width:100px}.mbar-seg{height:8px}
.pbar{display:flex;align-items:center;gap:6px;white-space:nowrap}.pbar-track{background:var(--cp-border);border-radius:8px;height:6px;width:64px;overflow:hidden;flex-shrink:0}
.pbar-fill{height:6px;border-radius:8px}.pbar-lbl{font-size:12px;font-variant-numeric:tabular-nums;min-width:30px}
.banner-manual{display:flex;gap:12px;align-items:flex-start;padding:12px 16px;margin-bottom:20px;border:1px solid var(--cp-border);border-left:4px solid var(--cp-violet);border-radius:.625rem;background:var(--cp-surface)}
.banner-icon{font-size:22px;color:var(--cp-violet);line-height:1}.banner-text{font-size:13px;line-height:1.6}
.batch-action,.batch-warn{padding:10px 16px;font-size:12px;line-height:1.6;border-left:3px solid var(--cp-violet);background:var(--cp-accent-soft)}
.batch-warn{border-left-color:var(--cp-danger)}.batch-warn.quar{border-left-color:var(--cp-warning)}
.filter-state{font-size:12px;font-weight:600;margin-right:6px}.filter-state .clear{margin-left:6px;font-size:12px;padding:2px 10px}
tr.userrow.filter-hidden{display:none}details.batch.filter-empty>summary{opacity:.45}details.batch.filter-empty>:not(summary){display:none}
tr.r-fail td{background:rgba(220,38,38,.07)}tr.r-quar td{background:rgba(217,119,6,.08)}tr.r-sync td{background:rgba(124,58,237,.06)}
tr.r-act td{background:rgba(0,120,212,.05)}tr.r-done td{background:rgba(22,163,74,.05)}
.err-type{color:var(--cp-danger);font-weight:600;font-size:12px}.quar-type{color:var(--cp-warning);font-weight:600;font-size:12px}
.err-msg{font-size:12px;margin-top:3px;white-space:normal;max-width:520px;color:var(--cp-text-muted)}
"@
        [void]$sb.Append((Get-ExHtmlHead -Title ("{0} | {1}" -f $Title, $stamp) -RefreshSeconds $AutoRefreshSeconds -ExtraStyle $extraStyle))

        # ---- HEADER: clickable tiles (data-filter-group = filter of the user rows) ----
        # Clicking a tile filters the users of the report by that group; clicking it again
        # clears the filter (script at the end of the file).
        $tile = {
            param($Class, $Group, $Label, $Value, $Note, $Tone)
            $data  = if ($null -ne $Group) { " data-filter-group='$Group'" } else { '' }
            $style = if ($Tone) { " style='--tone:$Tone'" } else { '' }
            "<article class='$Class'$data$style><span class='tile-label'>$Label</span><strong>$Value</strong><small>$Note</small></article>"
        }
        $refreshText = if ($AutoRefreshSeconds -gt 0) { '<br>Refreshed every {0} min' -f [math]::Round($AutoRefreshSeconds / 60) } else { '' }
        $box = "Mode <strong>$ReportMode</strong><br>$now$refreshText"
        if ($nbBatch -gt 0) {
            $tiles = @(
                (& $tile 'tile tile-primary clickable' 'final' 'Finalized' (Format-ExNumber $totalFinal) ("$globalPct% of $totalMbx mailbox(es)") '')
                (& $tile 'tile clickable' 'synced' 'Synced' (Format-ExNumber $totalSynced) 'Waiting for the manual completion (Step 21)' 'var(--cp-violet)')
                (& $tile 'tile clickable' 'active' 'Active / syncing' (Format-ExNumber $totalActive) 'Created, provisioning or syncing' 'var(--cp-info)')
            )
            if ($totalQuar -gt 0) { $tiles += (& $tile 'tile clickable' 'quarantined' 'Quarantined' (Format-ExNumber $totalQuar) 'Blocked by the Mailbox Replication service' 'var(--cp-warning)') }
            $tiles += (& $tile 'tile clickable' 'failed' 'Failed' (Format-ExNumber $totalFailed) 'Failed or stopped' $(if ($totalFailed -gt 0) { 'var(--cp-danger)' } else { 'var(--cp-success)' }))
            $tiles += (& $tile 'tile tile-tinted' '' 'Batches' (Format-ExNumber $nbBatch) ("$globalAvgPct% average sync") '')
            $extra = "<div class='distribution'>" +
                     "<div><div class='band-head'><span>Average sync</span><span>$globalAvgPct%</span></div><div class='track'><div class='fill' style='width:$globalAvgPct%;background:var(--cp-info)'></div></div></div>" +
                     "<div><div class='band-head'><span>Finalized mailboxes</span><span>$totalFinal / $globalPct%</span></div><div class='track'><div class='fill' style='width:$globalPct%;background:var(--cp-success)'></div></div></div></div>" +
                     "<div class='leg'><span><span class='leg-sq' style='background:var(--cp-success)'></span>Completed / finalized</span>" +
                     "<span><span class='leg-sq' style='background:var(--cp-violet)'></span>Synced (waiting for Step 21)</span>" +
                     "<span><span class='leg-sq' style='background:var(--cp-warning)'></span>Quarantined (MRS blocked)</span>" +
                     "<span><span class='leg-sq' style='background:var(--cp-info)'></span>Syncing / active</span>" +
                     "<span><span class='leg-sq' style='background:var(--cp-text-muted)'></span>Created / provisioning</span>" +
                     "<span><span class='leg-sq' style='background:var(--cp-danger)'></span>Failed / stopped</span>" +
                     "<span class='muted'>Click a tile to filter the mailboxes.</span></div>"
        } else {
            $tiles = @(); $extra = ''
        }
        $subtitle = "$nbBatch migration batch(es), $totalMbx mailbox(es): the state of every batch and every mailbox, from Get-MigrationBatch and the move request statistics (Step 20)."
        [void]$sb.Append((Get-ExHtmlHero -Title $Title -Subtitle $subtitle -BoxLabel 'Status' -BoxHtml $box -Tiles $tiles -ExtraHtml $extra))

        # ---- MANUAL COMPLETION BANNER ---------------------------------------
        # Explicitly states that the batches stay in 'Synced' until
        # Step21 (Complete-MigrationBatch) is launched manually.
        if ($nbBatch -gt 0) {
            [void]$sb.AppendLine("<div class='banner-manual'>")
            [void]$sb.AppendLine("  <span class='banner-icon'>&#9888;</span>")
            [void]$sb.AppendLine("  <div class='banner-text'>")
            [void]$sb.AppendLine("    <strong>MANUAL completion required.</strong>")
            [void]$sb.AppendLine("    The MigrationBatch objects were created with <code>SuspendWhenReadyToComplete</code>:")
            [void]$sb.AppendLine("    the <em>Synced</em> status indicates that a batch is ready to be finalized.")
            [void]$sb.AppendLine("    Run <code>.\Deploy-Exchange2019.ps1 -Step 21 -BatchNumber &lt;NN&gt; -Mode Apply</code>")
            [void]$sb.AppendLine("    (or <code>-BatchNumber ALL</code>) to run <code>Complete-MigrationBatch</code>.")
            [void]$sb.AppendLine("  </div>")
            [void]$sb.AppendLine("</div>")
        }

        if ($nbBatch -eq 0) {
            [void]$sb.AppendLine("<div class='card'><div class='card-hdr'>No data</div>")
            [void]$sb.AppendLine("<div class='card-body muted'>")
            [void]$sb.AppendLine("No <code>Batch\d{2}</code> MigrationBatch found. Run Step19 + Step20 (Apply) to create them.")
            [void]$sb.AppendLine("</div></div>")
            [void]$sb.Append((Get-ExHtmlFooter -Text 'This file contains mailbox addresses: store and share it accordingly.'))
            $sb.ToString() | Set-Content -Path $OutputPath -Encoding UTF8
            return
        }

        # ---- TOOLBAR + ACCORDIONS PER BATCH ---------------------------------
        # No filter buttons here: the filter is carried by the tiles of the header.
        [void]$sb.AppendLine("<div class='toolbar'>")
        [void]$sb.AppendLine("  <span id='filter-state' class='filter-state' style='display:none'></span>")
        [void]$sb.AppendLine("  <span class='label' style='margin:0'>$nbBatch migration batch(es)</span>")
        [void]$sb.AppendLine("  <button class='btn' onclick=""document.querySelectorAll('details.batch:not(.filter-empty)').forEach(function(d){d.open=true})"">&#9660;&thinsp;Expand all</button>")
        [void]$sb.AppendLine("  <button class='btn' onclick=""document.querySelectorAll('details.batch').forEach(function(d){d.open=false})"">&#9650;&thinsp;Collapse all</button>")
        [void]$sb.AppendLine("</div>")

        foreach ($b in ($Stats | Sort-Object Name)) {
            $bName    = [string]$b.Name
            $bStatus  = [string]$b.Status
            # Counters recomputed from Users[] (Exchange's batch.SyncedCount is only
            # incremented at the batch.Status=Synced transition, hence 0 too often).
            $bUsers   = @($b.Users)
            $bTot     = $bUsers.Count
            $bFin     = @($bUsers | Where-Object { $_.Status -in $grpFinal  }).Count
            $bSyn     = @($bUsers | Where-Object { $_.Status -in $grpSynced }).Count
            $bActive  = @($bUsers | Where-Object { $_.Status -in $grpActive }).Count
            $bFld     = @($bUsers | Where-Object { $_.Status -eq 'Failed' }).Count
            $bStopped = @($bUsers | Where-Object { $_.Status -eq 'Stopped' }).Count
            $bQuar    = @($bUsers | Where-Object { $_.StatusDetail -and ([string]$_.StatusDetail -match '^Stalled|Quarantine') }).Count

            # Average batch progress: average of the user-level PercentageComplete.
            # Distinct from $pFin (% of users 100% finalized): a batch where all the users
            # are Synced at 95% gives $bAvgPct=95 but $pFin=0 (none finalized yet).
            $bAvgPct = if ($bTot -gt 0) {
                [math]::Round((($bUsers | Measure-Object -Property PercentageComplete -Sum).Sum) / $bTot)
            } else { 0 }

            # Percentages for the multi-segment bar:
            #   Finalized (green) | Synced (orange = waiting) | Active (blue = in progress) | Failed (red)
            $pFin = if ($bTot -gt 0) { [math]::Round($bFin * 100 / $bTot) } else { 0 }
            $pSyn = if ($bTot -gt 0) { [math]::Round($bSyn * 100 / $bTot) } else { 0 }
            $pAct = if ($bTot -gt 0) { [math]::Round($bActive * 100 / $bTot) } else { 0 }
            $pFld = if ($bTot -gt 0) { [math]::Round($bFld * 100 / $bTot) } else { 0 }

            $barHtml = "<div class='mbar'>"
            if ($pFin -gt 0) { $barHtml += "<div class='mbar-seg' style='width:$pFin%;background:var(--cp-success)' title='Finalized'></div>" }
            if ($pSyn -gt 0) { $barHtml += "<div class='mbar-seg' style='width:$pSyn%;background:var(--cp-violet)' title='Synced (waiting completion)'></div>" }
            if ($pAct -gt 0) { $barHtml += "<div class='mbar-seg' style='width:$pAct%;background:var(--cp-info)' title='Active/Syncing'></div>" }
            if ($pFld -gt 0) { $barHtml += "<div class='mbar-seg' style='width:$pFld%;background:var(--cp-danger)' title='Failed'></div>" }
            $barHtml += "</div>"

            # Pills per counter (priority: Failed > Quarantined > Synced > Active > Finalized)
            $typePills = ''
            if ($bFld -gt 0)     { $typePills += "<span class='pill' style='background:var(--cp-danger)'>Failed&nbsp;$bFld</span>" }
            if ($bStopped -gt 0) { $typePills += "<span class='pill' style='background:var(--cp-danger)'>Stopped&nbsp;$bStopped</span>" }
            if ($bQuar -gt 0)    { $typePills += "<span class='pill' style='background:var(--cp-warning)'>Quarantined&nbsp;$bQuar</span>" }
            if ($bSyn -gt 0)     { $typePills += "<span class='pill' style='background:var(--cp-violet)'>Synced&nbsp;$bSyn</span>" }
            if ($bActive -gt 0)  { $typePills += "<span class='pill' style='background:var(--cp-info)'>Active&nbsp;$bActive</span>" }
            if ($bFin -gt 0)     { $typePills += "<span class='pill' style='background:var(--cp-success)'>Finalized&nbsp;$bFin</span>" }

            $statusColor = if ($clr[$bStatus]) { $clr[$bStatus] } else { $clr['default'] }
            $aid   = 's-' + ($bName -replace '[^a-zA-Z0-9]','-')
            # Auto-open if Failed, Quarantined or Synced (waiting completion = user action required)
            $openA = if ($bFld -gt 0 -or $bQuar -gt 0 -or $bStatus -eq 'Synced') { ' open' } else { '' }

            # "Action required" banner for the Synced / Quarantined / Failed batches
            $actionLine = ''
            if ($bQuar -gt 0) {
                $actionLine = "<div class='batch-warn quar'>&#9888; $bQuar mailbox(es) in MRS quarantine (StalledDueTo*). See details below (StatusDetail). Inspect with <code>Get-MoveRequestStatistics &lt;identity&gt; -IncludeReport</code>.</div>"
            } elseif ($bStatus -eq 'Synced') {
                $batchNum = ($bName -replace '^Batch','') -replace '^0+',''
                $actionLine = "<div class='batch-action'>&#9888; Ready for completion. Run: <code>.\Deploy-Exchange2019.ps1 -Step 21 -BatchNumber $batchNum -Mode Apply</code></div>"
            } elseif ($bFld -gt 0) {
                $actionLine = "<div class='batch-warn'>&#9888; $bFld mailbox(es) in Failed state. See details below (Message + FailureType).</div>"
            }

            [void]$sb.AppendLine("<details$openA id='$aid' class='batch' data-status='$(Esc $bStatus)'>")
            [void]$sb.AppendLine("  <summary>")
            [void]$sb.AppendLine("    <span class='acc-icon'>&#9654;</span>")
            [void]$sb.AppendLine("    <span class='acc-step'>$(Esc $bName)</span>")
            [void]$sb.AppendLine("    <span class='bdg' style='background:$statusColor'>$(Esc $bStatus)</span>")
            [void]$sb.AppendLine("    <span class='acc-cnt'>$bTot&thinsp;mailbox(es)</span>")
            [void]$sb.AppendLine("    <span class='acc-bar'>$barHtml</span>")
            [void]$sb.AppendLine("    <span class='acc-pct' title='Average sync = average PercentageComplete | Finalized = % of users at 100%'>$bAvgPct&thinsp;% sync &middot; $pFin&thinsp;% finalized</span>")
            [void]$sb.AppendLine("    <span class='acc-pills'>$typePills</span>")
            [void]$sb.AppendLine("  </summary>")
            if ($actionLine) { [void]$sb.AppendLine("  $actionLine") }
            [void]$sb.AppendLine("  <div class='tbl-wrap'><table>")
            [void]$sb.AppendLine("    <thead><tr>")
            [void]$sb.AppendLine("      <th style='min-width:240px'>Email / Identity</th>")
            [void]$sb.AppendLine("      <th style='min-width:120px'>Status</th>")
            [void]$sb.AppendLine("      <th style='min-width:130px'>Progress</th>")
            [void]$sb.AppendLine("      <th style='min-width:240px'>Detail / Error</th>")
            [void]$sb.AppendLine("      <th style='min-width:120px'>Target DB</th>")
            [void]$sb.AppendLine("      <th style='min-width:140px'>Last sync</th>")
            [void]$sb.AppendLine("    </tr></thead><tbody>")

            # Sort: Failed first, Completed/Finalized last
            $sortedUsers = @($b.Users) | Sort-Object @{
                Expression = { if ($statusSort[$_.Status]) { $statusSort[$_.Status] } else { 9 } }
            }, Identity

            foreach ($u in $sortedUsers) {
                $uStat = [string]$u.Status
                $sd    = [string]$u.StatusDetail
                $uQuar = $sd -and ($sd -match '^Stalled|Quarantine')
                $bdc   = if ($clr[$uStat]) { $clr[$uStat] } else { $clr['default'] }
                $rbg   = ''
                if ($uStat -in @('Failed','Stopped'))      { $rbg = 'r-fail' }
                elseif ($uQuar)                            { $rbg = 'r-quar' }
                elseif ($uStat -eq 'Synced')               { $rbg = 'r-sync' }
                elseif ($uStat -in @('Syncing','Active','IncrementalSync')) { $rbg = 'r-act' }
                elseif ($uStat -in @('Completed','CompletedWithErrors')) { $rbg = 'r-done' }

                $email = Esc ([string]$u.Identity)
                $pct   = [int]$u.PercentageComplete
                $pctW  = [math]::Min($pct, 100)
                $tdb   = Esc ([string]$u.TargetDatabase)
                $lastU = if ($u.LastUpdateTimestamp) { ([datetime]$u.LastUpdateTimestamp).ToString('yyyy-MM-dd HH:mm') } else { '<span class=em>-</span>' }

                $pbarHtml = "<div class='pbar'><div class='pbar-track'><div class='pbar-fill' style='width:$pctW%;background:$bdc'></div></div><span class='pbar-lbl'>$pct&thinsp;%</span></div>"

                # Status cell: main badge + Quarantined sub-badge (orange) if applicable.
                $statusCell = "<span class='bdg' style='background:$bdc'>$(Esc $uStat)</span>"
                if ($uQuar) {
                    $statusCell += "<div style='margin-top:3px'><span class='bdg' style='background:var(--cp-warning)' title='MoveRequestStatistics.StatusDetail'>$(Esc $sd)</span></div>"
                }

                # Failed error: show FailureType + Message in red.
                # Quarantined: show StatusDetail + MRS Message in orange (warning, not error).
                $detailHtml = if ($uStat -in @('Failed','Stopped')) {
                    $ft  = Esc ([string]$u.FailureType)
                    $msg = Esc ([string]$u.Error)
                    $errBlock = ''
                    if ($ft)  { $errBlock += "<div class='err-type'>$ft</div>" }
                    if ($msg) { $errBlock += "<div class='err-msg'>$msg</div>" }
                    if (-not $errBlock) { $errBlock = "<span class='em'>(no detail)</span>" }
                    $errBlock
                } elseif ($uQuar) {
                    $msg = Esc ([string]$u.Error)
                    $warnBlock = "<div class='quar-type'>MRS quarantined: $(Esc $sd)</div>"
                    if ($msg) { $warnBlock += "<div class='err-msg'>$msg</div>" }
                    $warnBlock
                } elseif ($u.SkippedItemCount -gt 0) {
                    "<span class='val'>Skipped items: $($u.SkippedItemCount)</span>"
                } else {
                    "<span class='em'>-</span>"
                }

                $quarAttr = if ($uQuar) { '1' } else { '0' }
                [void]$sb.AppendLine("    <tr class='userrow $rbg' data-status='$(Esc $uStat)' data-quar='$quarAttr'>")
                [void]$sb.AppendLine("      <td class='td-dn'>$email</td>")
                [void]$sb.AppendLine("      <td>$statusCell</td>")
                [void]$sb.AppendLine("      <td>$pbarHtml</td>")
                [void]$sb.AppendLine("      <td>$detailHtml</td>")
                [void]$sb.AppendLine("      <td><span class='val'>$tdb</span></td>")
                [void]$sb.AppendLine("      <td><span class='val'>$lastU</span></td>")
                [void]$sb.AppendLine("    </tr>")
            }

            [void]$sb.AppendLine("    </tbody></table></div>")
            [void]$sb.AppendLine("</details>")
        }

        # ---- BACK TO TOP + JS -----------------------------------------------
        [void]$sb.AppendLine('<script>')
        [void]$sb.AppendLine('(function(){')
        # Mapping group -> set of user statuses (must reflect $grp* on the PS side)
        [void]$sb.AppendLine('  var GROUPS = {')
        [void]$sb.AppendLine("    final:  ['Completed','CompletedWithErrors'],")
        [void]$sb.AppendLine("    synced: ['Synced'],")
        [void]$sb.AppendLine("    active: ['Syncing','IncrementalSync','Active','Provisioning','Provisioned','Created'],")
        [void]$sb.AppendLine("    failed: ['Failed','Stopped']")
        [void]$sb.AppendLine('  };')
        [void]$sb.AppendLine("  var LABELS = { final:'Finalized', synced:'Synced', active:'Active / Syncing', failed:'Failed', quarantined:'MRS Quarantined' };")
        [void]$sb.AppendLine('  var current = null;  // null = no filter')
        [void]$sb.AppendLine('  function applyFilter(){')
        [void]$sb.AppendLine("    var all = (current === null);")
        [void]$sb.AppendLine("    var quarOnly = (current === 'quarantined');")
        [void]$sb.AppendLine("    var set = (all || quarOnly) ? null : new Set(GROUPS[current] || []);")
        [void]$sb.AppendLine("    // 1) Filter each user row (quarantined = data-quar=1, orthogonal to Status)")
        [void]$sb.AppendLine("    document.querySelectorAll('tr.userrow').forEach(function(tr){")
        [void]$sb.AppendLine("      var keep;")
        [void]$sb.AppendLine("      if (all) keep = true;")
        [void]$sb.AppendLine("      else if (quarOnly) keep = tr.getAttribute('data-quar') === '1';")
        [void]$sb.AppendLine("      else keep = set.has(tr.getAttribute('data-status') || '');")
        [void]$sb.AppendLine("      if (keep) tr.classList.remove('filter-hidden');")
        [void]$sb.AppendLine("      else tr.classList.add('filter-hidden');")
        [void]$sb.AppendLine('    });')
        [void]$sb.AppendLine("    // 2) If a batch has no visible row: collapse it (greyed summary, hidden content)")
        [void]$sb.AppendLine("    //    But keep it visible so that it is clear it has no matching user.")
        [void]$sb.AppendLine("    document.querySelectorAll('details.batch').forEach(function(b){")
        [void]$sb.AppendLine("      var nUsers = b.querySelectorAll('tr.userrow').length;")
        [void]$sb.AppendLine("      var nVisible = b.querySelectorAll('tr.userrow:not(.filter-hidden)').length;")
        [void]$sb.AppendLine("      if (!all && nUsers > 0 && nVisible === 0) {")
        [void]$sb.AppendLine("        b.classList.add('filter-empty'); b.open = false;")
        [void]$sb.AppendLine("      } else {")
        [void]$sb.AppendLine("        b.classList.remove('filter-empty');")
        [void]$sb.AppendLine("        if (!all && nVisible > 0) { b.open = true; }")
        [void]$sb.AppendLine("      }")
        [void]$sb.AppendLine('    });')
        [void]$sb.AppendLine("    // 3) Update the visual state of the tiles + banner")
        [void]$sb.AppendLine("    document.querySelectorAll('.tile[data-filter-group]').forEach(function(t){")
        [void]$sb.AppendLine("      var g = t.getAttribute('data-filter-group');")
        [void]$sb.AppendLine("      t.classList.remove('tile-active','dimmed');")
        [void]$sb.AppendLine("      if (!g) return;  // 'Batches' tile does not filter")
        [void]$sb.AppendLine("      if (all) { /* neutral */ }")
        [void]$sb.AppendLine("      else if (g === current) t.classList.add('tile-active');")
        [void]$sb.AppendLine("      else t.classList.add('dimmed');")
        [void]$sb.AppendLine('    });')
        [void]$sb.AppendLine("    var fs = document.getElementById('filter-state');")
        [void]$sb.AppendLine("    if (all) { fs.style.display='none'; fs.innerHTML=''; }")
        [void]$sb.AppendLine("    else {")
        [void]$sb.AppendLine("      var totalVis = document.querySelectorAll('tr.userrow:not(.filter-hidden)').length;")
        [void]$sb.AppendLine("      fs.style.display=''; fs.innerHTML = 'Filter: <strong>'+(LABELS[current]||current)+'</strong> &middot; '+totalVis+' mailbox(es) <button class=""clear"" id=""clear-filter"">&#10005; Clear</button>';")
        [void]$sb.AppendLine("      document.getElementById('clear-filter').addEventListener('click', function(){ current=null; applyFilter(); });")
        [void]$sb.AppendLine('    }')
        [void]$sb.AppendLine('  }')
        [void]$sb.AppendLine("  document.querySelectorAll('.tile[data-filter-group]').forEach(function(t){")
        [void]$sb.AppendLine("    var g = t.getAttribute('data-filter-group'); if (!g) return;")
        [void]$sb.AppendLine("    t.addEventListener('click', function(){")
        [void]$sb.AppendLine("      current = (current === g) ? null : g;")
        [void]$sb.AppendLine("      applyFilter();")
        [void]$sb.AppendLine("    });")
        [void]$sb.AppendLine('  });')
        # Anchor navigation
        [void]$sb.AppendLine('  function goAnchor(){')
        [void]$sb.AppendLine('    var h=location.hash; if(!h)return;')
        [void]$sb.AppendLine('    var el=document.querySelector(h);')
        [void]$sb.AppendLine("    if(el&&el.tagName==='DETAILS'){el.open=true;setTimeout(function(){el.scrollIntoView({behavior:'smooth',block:'start'})},80);}")
        [void]$sb.AppendLine('  }')
        [void]$sb.AppendLine('  goAnchor();')
        [void]$sb.AppendLine("  window.addEventListener('hashchange',goAnchor);")
        [void]$sb.AppendLine('})();')
        [void]$sb.AppendLine('</script>')
        [void]$sb.Append((Get-ExHtmlFooter -Text 'This file contains mailbox addresses: store and share it accordingly.'))

        $sb.ToString() | Set-Content -Path $OutputPath -Encoding UTF8
    }

    # =========================================================================
    $badItem   = [int]$Config.Migration.BadItemLimit
    $largeItem = [int]$Config.Migration.LargeItemLimit
    $acceptLDL = [bool]$Config.Migration.AcceptLargeDataLoss

    # Follow mode: $env:FOLLOW = '1' or $Global:FollowMigration = $true
    $followMode = ($env:FOLLOW -in @('1','true','yes')) -or
                  ((Test-Path Variable:Global:FollowMigration) -and $Global:FollowMigration)

    Write-StepBanner -StepName '20' -Title 'Start the move requests' -Mode $Mode -Actions @(
        'Read MigrationPlan.csv (produced by step 19)',
        'Remove all existing MoveRequests before submission',
        'Assign a TargetDatabase per MR (round-robin over the Exchange 2019 databases)',
        'New-MoveRequest -SuspendWhenReadyToComplete (manual completion via Step21)',
        "BadItemLimit=$badItem  LargeItemLimit=$largeItem  AcceptLargeDataLoss=$acceptLDL",
        "Follow mode: $($followMode) - (enable with `$env:FOLLOW = '1'`)"
    )

    Reset-Report
    Initialize-ExchangeShell -Credential $Credential

    # --- Prerequisite: MigrationPlan.csv (Apply/Simulate only) ---------------
    $plan     = $null
    $planPath = Join-Path $OutputFolder 'MigrationPlan.csv'
    if ($Mode -ne 'Inventory') {
        if (-not (Test-Path $planPath)) {
            Write-Log "Migration plan not found: $planPath" -Level Error
            Write-Log "Run step 19 (PrepareMigration) first." -Level Error
            Save-Report -StepName 'Step20-RunMigration' | Out-Null
            return 1
        }
        $plan = Import-Csv -Path $planPath -Delimiter ';'
        Write-Log "Plan loaded: $($plan.Count) entries" -Level Sub
    }

    # --- Snapshot of the current state ---------------------------------------
    Write-Log "Current state of the MoveRequests..." -Level Sub
    $existingMR = @(Get-MoveRequest -ResultSize Unlimited -ErrorAction SilentlyContinue)
    $snapStats  = $null

    # Optional single OR multi-batch filter (set by the orchestrator via -FollowAfter
    # combined with -BatchNumber NN or -BatchNumber 'NN','NN',...). When set, the
    # HTML report only shows the target batch(es).
    # $script:followBatchFilter  : scalar string if single (helper back-compat)
    # $script:followBatchFilters : always an array, empty when there is no focus
    $script:followBatchFilter  = $null
    $script:followBatchFilters = @()
    if ($Global:FollowBatchFilter) {
        $items = @(@($Global:FollowBatchFilter) |
                    ForEach-Object { [string]$_ } |
                    Where-Object { $_ -match '^Batch\d{2}$' } |
                    Sort-Object -Unique)
        if ($items.Count -gt 0) {
            $script:followBatchFilters = $items
            if ($items.Count -eq 1) {
                $script:followBatchFilter = $items[0]
                Write-Log "FOLLOW mode: single-batch focus on $($items[0])" -Level Sub
            } else {
                Write-Log ("FOLLOW mode: multi-batch focus ({0}): {1}" -f $items.Count, ($items -join ', ')) -Level Sub
            }
        }
    }

    # Local helper: returns the list of official MigrationBatch objects (Step20).
    # Source of truth = Get-MigrationBatch (native Exchange object). Filtered by
    # name matching 'Batch\d{2}' (Step20 convention). Can additionally be
    # cross-checked against the plan via MigrationPlan.csv, and restricted to a single batch
    # via $script:followBatchFilter (focus mode -FollowAfter + -BatchNumber NN).
    function Get-OfficialMigrationBatches {
        # OPTIMIZATION single/multi-batch focus: Get-MigrationBatch -Identity targets
        # each batch directly, avoids serializing all the MigrationBatch objects of the org.
        if ($script:followBatchFilters.Count -gt 0) {
            $out = @()
            foreach ($name in $script:followBatchFilters) {
                $b = Get-MigrationBatch -Identity $name -ErrorAction SilentlyContinue
                if ($b) { $out += $b }
            }
            return $out
        }

        $batches = Get-MigrationBatch -ErrorAction SilentlyContinue | Where-Object {
            [string]$_.Identity -match '^Batch\d{2}$'
        }
        if (-not $batches) { return @() }

        # Optional extra filter via MigrationPlan.csv if available (additional defense
        # against names colliding with batches created by hand).
        $planFile = Join-Path $OutputFolder 'MigrationPlan.csv'
        if (Test-Path $planFile) {
            try {
                $rows = Import-Csv $planFile -Delimiter ';' -ErrorAction Stop
                $expected = @($rows | ForEach-Object { 'Batch{0:D2}' -f [int]$_.Batch } | Sort-Object -Unique)
                if ($expected.Count -gt 0) {
                    return @($batches | Where-Object { [string]$_.Identity -in $expected })
                }
            } catch { }
        }
        return @($batches)
    }

    # Backward-compatible helper: Get-ExpectedBatchNames is still useful to filter
    # the MRs (without an underlying MigrationBatch, e.g. PublicFolder outside a batch).
    function Get-ExpectedBatchNames {
        $officialBatches = Get-OfficialMigrationBatches
        if ($officialBatches.Count -gt 0) {
            return @($officialBatches | ForEach-Object { [string]$_.Identity })
        }
        # Fallback: read plan.csv if there is no MigrationBatch (pre-Apply)
        $planFile = Join-Path $OutputFolder 'MigrationPlan.csv'
        if (Test-Path $planFile) {
            try {
                $rows = Import-Csv $planFile -Delimiter ';' -ErrorAction Stop
                $numbers = @($rows | ForEach-Object { [int]$_.Batch } | Sort-Object -Unique)
                if ($numbers.Count -gt 0) {
                    return @($numbers | ForEach-Object { 'Batch{0:D2}' -f $_ })
                }
            } catch { }
        }
        return $null
    }

    # Local helper: full snapshot for the HTML report, batch-centric structure.
    # Returns an array of PSCustomObject, one per official MigrationBatch:
    #   { Name, Status, TotalCount, ActiveCount, SyncedCount, FinalizedCount,
    #     FailedCount, StoppedCount, CreatedDate, CompleteAfter, Users[] }
    # Users[] contains one entry per mailbox of the batch with:
    #   { Identity, Mail, DisplayName, Status, PercentageComplete, Error,
    #     LastUpdateTimestamp, TargetDatabase, SkippedItemCount }
    #
    # Source: Get-MigrationBatch (batch-level) + Get-MigrationUser | Get-MigrationUserStatistics
    # (mailbox-level). Enriched with Get-MoveRequestStatistics to get
    # TargetDatabase (not exposed on MigrationUserStatistics).
    function Get-MbSnapshot {
        $batches = Get-OfficialMigrationBatches
        if ($batches.Count -eq 0) { return @() }

        # Local helper: strip the "MigrationService:" prefix to normalize to the official name
        $normBatch = { param($n) if ($n -match '^MigrationService:(.+)$') { $matches[1] } else { [string]$n } }

        # Lookup of TargetDatabase via Get-MoveRequestStatistics. WARNING: the MRs created
        # by MigrationBatch have BatchName='MigrationService:BatchNN', hence the extended regex.
        #
        # OPTIMIZATION single-batch focus: if $script:followBatchFilter is set,
        # we filter directly server-side via -BatchName 'MigrationService:BatchNN'.
        # Without this filter, Get-MoveRequest serializes ALL the MRs of the organization
        # (5+ min for 455 MRs), versus ~1-2s for ~40 MRs. The server-side filter avoids the
        # full round-trip + serialization.
        if ($script:followBatchFilters.Count -gt 0) {
            $allMrs = @()
            foreach ($name in $script:followBatchFilters) {
                $mrs = Get-MoveRequest -BatchName ("MigrationService:" + $name) -ErrorAction SilentlyContinue
                if ($mrs) { $allMrs += $mrs }
            }
        } else {
            $allMrs = Get-MoveRequest -ErrorAction SilentlyContinue |
                      Where-Object { $_.BatchName -and ((& $normBatch $_.BatchName) -match '^Batch\d{2}$') }
        }

        # MigrationUser.Identity is the email (UPN/SMTP); MoveRequest.Alias is the AD alias.
        # When the AD alias != the local part of the email (e.g. 'jdupont' vs 'jean.dupont@...'),
        # an index on the alias alone misses the match -> TargetDb and MR % are lost.
        # So we resolve alias->email via Get-Recipient (script: cache so as not to
        # pay the remoting round-trips again on each HTML refresh).
        if (-not $script:_mbSnapAliasEmailCache) { $script:_mbSnapAliasEmailCache = @{} }
        $aliasToEmail = $script:_mbSnapAliasEmailCache

        $mrStats = @()
        if ($allMrs) {
            $toResolve = @($allMrs | Where-Object {
                $_.Alias -and -not $aliasToEmail.ContainsKey([string]$_.Alias)
            })
            foreach ($mr in $toResolve) {
                try {
                    $rec = Get-Recipient -Identity ([string]$mr.Identity) -ErrorAction Stop
                    if ($rec -and $rec.PrimarySmtpAddress) {
                        $aliasToEmail[[string]$mr.Alias] = ([string]$rec.PrimarySmtpAddress).ToLower()
                    }
                } catch { }
            }

            $mrStats = @($allMrs | Get-MoveRequestStatistics -ErrorAction SilentlyContinue |
                Select-Object DisplayName, Alias, BatchName, TargetDatabase, Status, StatusDetail, PercentComplete,
                              Message, FailureType, LastUpdateTimestamp)
        }
        # Double index: 'Batch01||email::xxx' (preferred) + 'Batch01||alias::xxx' (fallback)
        $mrByKey = @{}
        foreach ($s in $mrStats) {
            $normName = & $normBatch $s.BatchName
            $alias    = [string]$s.Alias
            $mrByKey["$normName||alias::$($alias.ToLower())"] = $s
            if ($aliasToEmail.ContainsKey($alias)) {
                $mrByKey["$normName||email::$($aliasToEmail[$alias])"] = $s
            }
        }

        $snapshot = @()
        foreach ($b in $batches) {
            $bid = [string]$b.Identity
            $users = Get-MigrationUser -BatchId $bid -ErrorAction SilentlyContinue
            $userStats = @()
            if ($users) {
                $userStats = @($users | Get-MigrationUserStatistics -ErrorAction SilentlyContinue)
            }
            $userRows = foreach ($u in $userStats) {
                $email      = ([string]$u.Identity).ToLower()
                $aliasGuess = if ($email -match '^([^@]+)@') { $matches[1] } else { $email }
                # Cascading lookup: email first (key resolved via Get-Recipient),
                # alias derived from the local part of the email as a fallback.
                $mrInfo = $mrByKey["$bid||email::$email"]
                if (-not $mrInfo) { $mrInfo = $mrByKey["$bid||alias::$aliasGuess"] }

                $tgtDb      = if ($mrInfo) { [string]$mrInfo.TargetDatabase } else { '' }
                $errMsg     = if ($u.Error) { [string]$u.Error } else { '' }
                if (-not $errMsg -and $mrInfo -and $mrInfo.Message) { $errMsg = [string]$mrInfo.Message }
                $failType   = if ($mrInfo) { [string]$mrInfo.FailureType } else { '' }
                $lastUpdate = if ($u.LastSuccessfulSyncTime) { $u.LastSuccessfulSyncTime } `
                              elseif ($mrInfo) { $mrInfo.LastUpdateTimestamp } `
                              else { $null }
                # PercentComplete: MoveRequestStatistics is the reliable source.
                # MigrationUserStatistics.PercentComplete often stays at 0 even when Synced.
                $pct = 0
                if ($mrInfo -and [int]$mrInfo.PercentComplete -gt 0) { $pct = [int]$mrInfo.PercentComplete }
                elseif ($u.PercentComplete) { $pct = [int]$u.PercentComplete }
                # Safety net: a Synced/Completed user without a % is necessarily >= 95%
                if ($pct -eq 0) {
                    $st = [string]$u.Status
                    if ($st -in @('Completed','CompletedWithErrors')) { $pct = 100 }
                    elseif ($st -eq 'Synced') { $pct = 95 }
                }

                # StatusDetail comes from MoveRequestStatistics (e.g. StalledDueToMRS_Quarantined,
                # StalledDueToTarget_DiskLatency...): essential to spot the users
                # blocked on the MRS side while MigrationUser.Status stays 'Synced'.
                $statusDetail = if ($mrInfo -and $mrInfo.StatusDetail) { [string]$mrInfo.StatusDetail } else { '' }

                [PSCustomObject]@{
                    Identity            = $email
                    Alias               = $aliasGuess
                    DisplayName         = [string]$u.RecipientType + ' - ' + $email   # MigrationUser does not expose DisplayName directly
                    Status              = [string]$u.Status
                    StatusDetail        = $statusDetail
                    PercentageComplete  = $pct
                    Error               = $errMsg
                    FailureType         = $failType
                    LastUpdateTimestamp = $lastUpdate
                    TargetDatabase      = $tgtDb
                    SkippedItemCount    = [int]$u.SkippedItemCount
                }
            }

            # If some mailboxes have an MR but no MigrationUser (e.g. PublicFolder
            # via New-MoveRequest outside a MigrationBatch), we attach them to the batch via
            # their BatchName label.
            $mrOnly = $mrStats | Where-Object {
                $_.BatchName -eq $bid -and
                -not ($userStats | Where-Object { ([string]$_.Identity -split '@')[0] -ieq [string]$_.Alias })
            }
            foreach ($mr in $mrOnly) {
                $userRows += [PSCustomObject]@{
                    Identity            = [string]$mr.Alias
                    Alias               = [string]$mr.Alias
                    DisplayName         = [string]$mr.DisplayName
                    Status              = [string]$mr.Status
                    StatusDetail        = [string]$mr.StatusDetail
                    PercentageComplete  = [int]$mr.PercentComplete
                    Error               = [string]$mr.Message
                    FailureType         = [string]$mr.FailureType
                    LastUpdateTimestamp = $mr.LastUpdateTimestamp
                    TargetDatabase      = [string]$mr.TargetDatabase
                    SkippedItemCount    = 0
                }
            }

            $snapshot += [PSCustomObject]@{
                Name           = $bid
                Status         = [string]$b.Status
                TotalCount     = [int]$b.TotalCount
                ActiveCount    = [int]$b.ActiveCount
                SyncedCount    = [int]$b.SyncedCount
                FinalizedCount = [int]$b.FinalizedCount
                FailedCount    = [int]$b.FailedCount
                StoppedCount   = [int]$b.StoppedCount
                CreatedDate    = $b.CreationDateTime
                CompleteAfter  = $b.CompleteAfter
                Users          = @($userRows)
            }
        }
        return $snapshot
    }

    # Backward-compatible alias: the old code called Get-MrSnapshot, we keep the name
    # but it now returns an array of MigrationBatch (not flat MRs).
    function Get-MrSnapshot { Get-MbSnapshot }

    # Distinguish TOTAL MRs (raw, all sources combined) vs MRs DRIVEN
    # by Step19/20 (BatchName filter matching the plan list or regex 'Batch\d{2}').
    # NOTE: MoveRequests created by MigrationBatch have BatchName='MigrationService:BatchNN'.
    # We normalize by stripping the prefix to compare with the official names.
    function Convert-BatchNameToOfficial {
        param([string]$Raw)
        if (-not $Raw) { return '' }
        if ($Raw -match '^MigrationService:(.+)$') { return $matches[1] }
        return $Raw
    }
    $expectedNames    = Get-ExpectedBatchNames
    $inScopeMR        = @($existingMR | Where-Object {
        $_.BatchName -and
        (((Convert-BatchNameToOfficial -Raw $_.BatchName) -match '^Batch\d{2}$') -and
         ($expectedNames -eq $null -or (Convert-BatchNameToOfficial -Raw $_.BatchName) -in $expectedNames))
    })
    $outOfScopeCount  = $existingMR.Count - $inScopeMR.Count

    if ($existingMR.Count -gt 0) {
        Write-Log ("MRs detected: {0} in total - {1} driven by Step19/20 - {2} out of scope (Step18, manual MRs, etc.)" -f `
                   $existingMR.Count, $inScopeMR.Count, $outOfScopeCount) -Level Info
        if ($inScopeMR.Count -gt 0) {
            $snapStats = Get-MrSnapshot
            $byStatus  = $snapStats | Group-Object Status
            foreach ($g in $byStatus) {
                Write-Log "  $($g.Name): $($g.Count)" -Level Info
            }
            if ($Mode -ne 'Inventory') {
                $snapStats | Export-Csv -Path (Join-Path $OutputFolder 'MigrationStatus.csv') `
                    -NoTypeInformation -Encoding UTF8 -Delimiter ';'
            }
        } else {
            Write-Log "  No MR driven by Step19/20 (the report will be empty)." -Level Sub
        }
    } else {
        Write-Log "  No existing MoveRequest." -Level Sub
    }

    # --- Inventory mode (without FOLLOW): snapshot only, no HTML -----------
    if ($Mode -eq 'Inventory' -and -not $followMode) {
        Add-Report -Step '20-Move' -Target 'GLOBAL' -Action 'Snapshot MoveRequest' `
                   -Status Inventoried `
                   -AfterValue ("MRs driven by Step19/20: {0} | Org total: {1} (of which {2} out of scope)" -f `
                                 $inScopeMR.Count, $existingMR.Count, $outOfScopeCount)
        Save-Report -StepName 'Step20-RunMigration' | Out-Null
        return 0
    }

    # --- FOLLOW mode: HTML report + polling loop ----------------------------
    if ($followMode) {
        # Dynamic file name to allow 2 FOLLOW sessions in parallel:
        #  - global Step20 session -Follow  -> MigrationStatus.html
        #  - focus Step21 session -FollowAfter -BatchNumber 01 -> MigrationStatus-Batch01.html
        # Without this suffix, the 2 sessions would overwrite each other (same path).
        $htmlName = switch ($script:followBatchFilters.Count) {
            0       { 'MigrationStatus.html' }
            1       { "MigrationStatus-$($script:followBatchFilters[0]).html" }
            default {
                $sorted = $script:followBatchFilters | Sort-Object
                'MigrationStatus-{0}-{1}.html' -f $sorted[0], $sorted[-1]
            }
        }
        $htmlPath = Join-Path $OutputFolder $htmlName

        # Polling interval (in minutes). Default 60min. Sources by priority:
        #   1. $env:FOLLOW_INTERVAL = '<minutes>'         (session override)
        #   2. $Global:FollowMigrationInterval            (passed by the orchestrator via -FollowInterval)
        #   3. Default 60 minutes
        # Set 0 to generate once without looping.
        $intervalMin = 60
        if ($Global:FollowMigrationInterval -is [int] -and $Global:FollowMigrationInterval -ge 0) {
            $intervalMin = [int]$Global:FollowMigrationInterval
        }
        if ($env:FOLLOW_INTERVAL -match '^\d+$') { $intervalMin = [int]$env:FOLLOW_INTERVAL }
        $refreshSec  = if ($intervalMin -gt 0) { $intervalMin * 60 } else { 0 }

        # ----- 1st generation ------------------------------------------------
        # $snapStats is now an array of MigrationBatch (see Get-MbSnapshot).
        # For the title, we aggregate FinalizedCount / TotalCount over all the batches.
        # In single-batch focus mode (-FollowAfter + -BatchNumber NN), the title
        # explicitly mentions the target batch.
        $titlePrefix = switch ($script:followBatchFilters.Count) {
            0       { 'Migration status' }
            1       { "$($script:followBatchFilters[0]) status (focus)" }
            default { "Status of $($script:followBatchFilters.Count) batches (focus: $($script:followBatchFilters -join ', '))" }
        }
        $titleHtml = if ($snapStats) {
            $tFin = ($snapStats | Measure-Object -Property FinalizedCount -Sum).Sum
            $tTot = ($snapStats | Measure-Object -Property TotalCount     -Sum).Sum
            if (-not $tFin) { $tFin = 0 }; if (-not $tTot) { $tTot = 0 }
            "$titlePrefix - $tFin / $tTot mailbox(es) finalized"
        } else { 'Exchange 2019 migration status' }

        New-MigrationStatusHtml -Stats $snapStats -OutputPath $htmlPath -ReportMode $Mode `
            -Title $titleHtml -AutoRefreshSeconds $refreshSec
        Write-Log "Follow HTML report: $htmlPath" -Level Success

        # Automatic opening in the default browser (1st generation only).
        # The browser then refreshes by itself via meta http-equiv refresh;
        # the following polling iterations do not re-open it (to avoid piling up tabs).
        try {
            Invoke-Item -Path $htmlPath -ErrorAction Stop
            Write-Log "  Opening the HTML in the default browser..." -Level Sub
        } catch {
            Write-Log "  Unable to open the HTML automatically: $($_.Exception.Message)" -Level Warning
        }

        $batchCount = @($snapStats | Where-Object { $_ }).Count
        $tFinSum = ($snapStats | Measure-Object -Property FinalizedCount -Sum).Sum
        $tTotSum = ($snapStats | Measure-Object -Property TotalCount     -Sum).Sum
        if (-not $tFinSum) { $tFinSum = 0 }; if (-not $tTotSum) { $tTotSum = 0 }
        Add-Report -Step '20-Move' -Target 'GLOBAL' -Action 'Follow-Html' -Status Inventoried `
                   -AfterValue $htmlPath `
                   -Detail "Batches=$batchCount | Finalized=$tFinSum/$tTotSum | Interval=${intervalMin}min"
        Save-Report -StepName 'Step20-RunMigration' | Out-Null

        if ($intervalMin -le 0) {
            Write-Log "FOLLOW mode (one-shot, FOLLOW_INTERVAL=0) - HTML generated, exiting." -Level Info
            return 0
        }

        # ----- Polling loop --------------------------------------------------
        # In single-batch focus mode: the loop exits automatically when the target
        # batch reaches a terminal Status (Completed / CompletedWithErrors / Failed).
        # In multi-batch mode: endless loop until Ctrl+C (long-term follow-up).
        Write-Log ("=" * 70) -Level Step
        if ($script:followBatchFilters.Count -eq 1) {
            Write-Log "FOLLOW mode, focus on $($script:followBatchFilters[0]): polling every ${intervalMin}min." -Level Step
            Write-Log "Automatic exit when $($script:followBatchFilters[0]) is Completed (or Ctrl+C)." -Level Sub
        } elseif ($script:followBatchFilters.Count -gt 1) {
            Write-Log ("FOLLOW mode, focus on {0} batches ({1}): polling every {2}min." -f $script:followBatchFilters.Count, ($script:followBatchFilters -join ', '), $intervalMin) -Level Step
            Write-Log "Automatic exit when all the focus batches are Completed (or Ctrl+C)." -Level Sub
        } else {
            Write-Log "FOLLOW mode: polling every ${intervalMin}min. Ctrl+C to exit." -Level Step
        }
        Write-Log "The browser reloads by itself via <meta refresh content='$refreshSec'>." -Level Sub
        Write-Log "To change: `$env:FOLLOW_INTERVAL = '<minutes>' (0=disabled)" -Level Sub
        Write-Log ("=" * 70) -Level Step

        # Terminal statuses that trigger an exit in focus mode
        $terminalStatuses = @('Completed','CompletedWithErrors','Failed')

        $iter = 1
        while ($true) {
            Start-Sleep -Seconds ($intervalMin * 60)
            $iter++
            try {
                $snap = Get-MrSnapshot
                # Aggregation of the mailbox totals over all the MigrationBatch objects
                $tFin = ($snap | Measure-Object -Property FinalizedCount -Sum).Sum
                $tTot = ($snap | Measure-Object -Property TotalCount     -Sum).Sum
                $tSyn = ($snap | Measure-Object -Property SyncedCount    -Sum).Sum
                $tFld = ($snap | Measure-Object -Property FailedCount    -Sum).Sum
                if (-not $tFin) { $tFin = 0 }; if (-not $tTot) { $tTot = 0 }
                if (-not $tSyn) { $tSyn = 0 }; if (-not $tFld) { $tFld = 0 }
                $newTitle = "$titlePrefix - $tFin / $tTot mailbox(es) finalized"

                New-MigrationStatusHtml -Stats $snap -OutputPath $htmlPath -ReportMode $Mode `
                    -Title $newTitle -AutoRefreshSeconds $refreshSec

                Write-Log ("[iter #{0}] {1} - {2} batch(es) | {3}/{4} Finalized | {5} Synced | {6} Failed | HTML refreshed" -f `
                    $iter, (Get-Date -Format 'HH:mm:ss'), @($snap).Count, $tFin, $tTot, $tSyn, $tFld) -Level Info

                # Automatic exit condition in focus mode (single OR multi-batch):
                # all the focus batches must have reached a terminal Status.
                if ($script:followBatchFilters.Count -gt 0 -and @($snap).Count -gt 0) {
                    $focusEntries = @($snap | Where-Object { [string]$_.Name -in $script:followBatchFilters })
                    $focusTerminalCount = @($focusEntries | Where-Object { [string]$_.Status -in $terminalStatuses }).Count
                    if ($focusEntries.Count -eq $script:followBatchFilters.Count -and $focusTerminalCount -eq $script:followBatchFilters.Count) {
                        $detail = ($focusEntries | ForEach-Object { "$([string]$_.Name)=$([string]$_.Status)" }) -join ', '
                        Write-Log ("=" * 70) -Level Step
                        if ($script:followBatchFilters.Count -eq 1) {
                            Write-Log ("Batch {0} reached a terminal Status: {1}" -f $script:followBatchFilters[0], ([string]$focusEntries[0].Status)) -Level Success
                        } else {
                            Write-Log ("All {0} focus batches are in a terminal Status: {1}" -f $script:followBatchFilters.Count, $detail) -Level Success
                        }
                        Write-Log ("Finalized: {0}/{1} | Failed: {2}" -f $tFin, $tTot, $tFld) -Level Sub
                        Write-Log "Final HTML available: $htmlPath" -Level Sub
                        Write-Log "Automatic exit from the FOLLOW loop (focus mode)." -Level Step
                        Write-Log ("=" * 70) -Level Step

                        # Regenerate the HTML without meta refresh (frozen page = "done")
                        New-MigrationStatusHtml -Stats $snap -OutputPath $htmlPath -ReportMode $Mode `
                            -Title $newTitle -AutoRefreshSeconds 0
                        break
                    }
                }
            } catch {
                Write-Log "[iter #$iter] Error: $($_.Exception.Message)" -Level Warning
            }
        }
        return 0
    }

    # =========================================================================
    # APPLY / SIMULATE
    # =========================================================================

    # --- Exchange 2019 databases (round-robin) -------------------------------
    $ex2019Dbs = @(Get-MailboxDatabase -ErrorAction Stop |
                   Where-Object { Test-IsExchange2019Server -ServerName $_.Server.Name })
    $syntheticDbs = $false

    # In Simulate, if Step10 did not really create the databases, we generate the
    # target names from DatabaseLayout to be able to simulate the round-robin.
    # $syntheticDbs=$true signals that the DBs are fictitious -> New-MoveRequest cannot
    # be called even with -WhatIf (the cmdlet validates the TargetDB).
    if (-not $ex2019Dbs -and $Mode -eq 'Simulate' -and $Config.DatabaseLayout) {
        $dl    = $Config.DatabaseLayout
        $pad   = '{0:D' + [int]$dl.DatabaseDigits + '}'
        $names = @(
            for ($i = 0; $i -lt [int]$dl.DatabaseCount; $i++) {
                "$($dl.DatabasePrefix)" + ($pad -f ([int]$dl.DatabaseStartIndex + $i))
            }
        )
        $ex2019Dbs = $names | ForEach-Object { [PSCustomObject]@{ Name = $_ } }
        $syntheticDbs = $true
        Write-Log "No Exchange 2019 database found, generating the names from DatabaseLayout: $($names -join ', ')" -Level Warning
    }

    if (-not $ex2019Dbs) {
        Write-Log "No Exchange 2019 database available." -Level Error
        Save-Report -StepName 'Step20-RunMigration' | Out-Null
        return 1
    }
    Write-Log "Target databases ($($ex2019Dbs.Count)): $($ex2019Dbs.Name -join ', ')" -Level Sub

    # =========================================================================
    # Refactor v1.2: use of New-MigrationBatch -Local instead of individual
    # New-MoveRequest calls. Advantages:
    #   - Appears in EAC > Migration > Batches (centralized management)
    #   - Step21 uses Complete-MigrationBatch (1 command per batch instead of N)
    #   - The report reflects the native Exchange MigrationBatch semantics
    # Limitations:
    #   - PublicFolder mailboxes: not supported by MigrationBatch -Local
    #     -> handled separately via New-MoveRequest -PublicFolder (outside a batch)
    #   - System mailboxes (Arbitration/AuditLog/...): handled by Step18
    # =========================================================================

    # --- Removal: MigrationBatch + orphan MoveRequests -----------------------
    $existingBatches = @(Get-MigrationBatch -ErrorAction SilentlyContinue | Where-Object { $_.Identity -match '^Batch\d{2}$' })
    if ($existingBatches.Count -gt 0) {
        Write-Log "Removing $($existingBatches.Count) existing MigrationBatch(es)..." -Level Step
        foreach ($mb in $existingBatches) {
            $mbName = [string]$mb.Identity
            if ($Mode -eq 'Apply') {
                try {
                    Remove-MigrationBatch -Identity $mbName -Confirm:$false -Force -ErrorAction Stop
                    Add-Report -Step '20-Move' -Target $mbName -Action 'Remove-MigrationBatch' `
                               -Status Success -Detail "Previous status: $($mb.Status)"
                } catch {
                    Write-Log "  Error removing $mbName - $($_.Exception.Message)" -Level Warning
                    Add-Report -Step '20-Move' -Target $mbName -Action 'Remove-MigrationBatch' `
                               -Status Failed -Detail $_.Exception.Message
                }
            } else {
                Add-Report -Step '20-Move' -Target $mbName -Action 'Remove-MigrationBatch' `
                           -Status Simulated -Detail "Status: $($mb.Status)"
            }
        }
    }
    # Orphan MRs (e.g. old submission via direct New-MoveRequest) - we wipe them
    if ($existingMR.Count -gt 0) {
        Write-Log "Removing $($existingMR.Count) orphan MoveRequest(s)..." -Level Step
        foreach ($mr in $existingMR) {
            $mrLabel = if ($mr.DisplayName) { $mr.DisplayName } else { $mr.Alias }
            if ($Mode -eq 'Apply') {
                try {
                    Remove-MoveRequest -Identity $mr.Alias -Confirm:$false -ErrorAction Stop
                    Add-Report -Step '20-Move' -Target $mrLabel -Action 'Remove-MoveRequest (orphan)' `
                               -Status Success -Detail "Previous status: $($mr.Status)"
                } catch {
                    Write-Log "  Error removing $mrLabel - $($_.Exception.Message)" -Level Warning
                }
            }
        }
    }

    # --- Consolidation of the Primary/Archive of the same mailbox in the same batch -
    # If Step19 split the Primary and the Archive of the same mailbox into different
    # batches, we regroup them on the Primary's batch (MigrationBatch does not
    # support a mailbox being in 2 batches simultaneously).
    $primaryByMbx = @{}
    foreach ($row in ($plan | Where-Object { $_.Type -eq 'Primary' })) {
        $primaryByMbx[$row.PrimarySmtpAddress] = [int]$row.Batch
    }
    $consolidated = @()
    foreach ($row in $plan) {
        $effectiveBatch = if ($row.Type -eq 'Archive' -and $primaryByMbx.ContainsKey($row.PrimarySmtpAddress)) {
            [int]$primaryByMbx[$row.PrimarySmtpAddress]
        } else { [int]$row.Batch }
        $consolidated += [PSCustomObject]@{
            Original      = $row
            BatchNum      = $effectiveBatch
            EmailAddress  = $row.PrimarySmtpAddress
            Type          = $row.Type
            RecipientType = $row.RecipientTypeDetails
            Alias         = $row.Alias
        }
    }

    # --- Submission per batch ------------------------------------------------
    $dbIndex   = 0
    $byBatch   = $consolidated | Group-Object BatchNum | Sort-Object { [int]$_.Name }
    foreach ($g in $byBatch) {
        $batchNum  = [int]$g.Name
        $batchName = 'Batch{0:D2}' -f $batchNum

        # Split: PublicFolder vs the rest (PublicFolder -> MoveRequest outside a batch)
        $pfRows  = @($g.Group | Where-Object { $_.RecipientType -eq 'PublicFolderMailbox' })
        $mbxRows = @($g.Group | Where-Object { $_.RecipientType -ne 'PublicFolderMailbox' })

        # Sub-consolidation: for each unique mailbox, we possibly combine
        # Primary + Archive into a single CSV entry with TargetDatabase and
        # TargetArchiveDatabase. Round-robin over the Exchange 2019 databases.
        $csvRows = @()
        $perEmail = $mbxRows | Group-Object EmailAddress
        foreach ($eg in $perEmail) {
            $email = $eg.Name
            $hasPrimary = $eg.Group | Where-Object Type -eq 'Primary'
            $hasArchive = $eg.Group | Where-Object Type -eq 'Archive'

            $tgtPrim = if ($hasPrimary) { $ex2019Dbs[$dbIndex % $ex2019Dbs.Count].Name } else { '' }
            if ($hasPrimary) { $dbIndex++ }
            $tgtArch = if ($hasArchive) { $ex2019Dbs[$dbIndex % $ex2019Dbs.Count].Name } else { '' }
            if ($hasArchive) { $dbIndex++ }

            $csvRows += [PSCustomObject]@{
                EmailAddress          = $email
                TargetDatabase        = $tgtPrim
                TargetArchiveDatabase = $tgtArch
            }
        }

        $detailBatch = "Mailboxes=$($csvRows.Count) | PublicFolder=$($pfRows.Count) | TotalEntries=$($g.Count)"

        if ($syntheticDbs) {
            Add-Report -Step '20-Move' -Target $batchName -Action 'New-MigrationBatch -Local' `
                       -Status Simulated -BeforeValue 'No MigrationBatch (simulated databases from Step10)' `
                       -AfterValue '(simulation - not applied)' -Detail $detailBatch
            continue
        }

        Invoke-Action -Step '20-Move' -Target $batchName -Action 'New-MigrationBatch -Local' `
            -Detail $detailBatch `
            -InventoryScript {
                $b = Get-MigrationBatch -Identity $batchName -ErrorAction SilentlyContinue
                if ($b) { "Status=$($b.Status); TotalCount=$($b.TotalCount)" } else { 'No MigrationBatch' }
            } `
            -PreCheckScript { return $false } `
            -ActionScript {
                if ($csvRows.Count -gt 0) {
                    # New-MigrationBatch -CSVData expects byte[] - we build an in-memory CSV
                    $csvText = ($csvRows | ConvertTo-Csv -NoTypeInformation -Delimiter ',') -join "`r`n"
                    $csvBytes = [System.Text.Encoding]::UTF8.GetBytes($csvText)

                    # Known pitfalls with remoting splat:
                    #   - -AutoStart / -AutoComplete are SWITCHes => do not splat with $false
                    #     (the default for -Local is already $false, so we omit them)
                    #   - -LargeItemLimit splatted with 0 triggers "Parameter set cannot be resolved"
                    #     (internal Exchange validation). We omit it when =0 (Exchange default = 0 anyway).
                    #   - -BadItemLimit splat works even with 0. It can be passed.
                    $params = @{
                        Name         = $batchName
                        Local        = $true
                        CSVData      = $csvBytes
                        BadItemLimit = $badItem
                        ErrorAction  = 'Stop'
                    }
                    if ($largeItem -gt 0) { $params['LargeItemLimit'] = $largeItem }
                    New-MigrationBatch @params -WhatIf:([bool]($Mode -eq 'Simulate')) | Out-Null

                    if ($Mode -eq 'Apply') {
                        Start-MigrationBatch -Identity $batchName -ErrorAction Stop
                        Write-Log "  $batchName - started ($($csvRows.Count) mailbox(es))" -Level Sub
                    }
                }
                # Special case PublicFolder: New-MoveRequest outside a batch (MigrationBatch -Local does not support it)
                foreach ($pf in $pfRows) {
                    $pfAlias = $pf.Alias
                    $pfDb    = $ex2019Dbs[$dbIndex % $ex2019Dbs.Count].Name
                    $dbIndex++
                    $pfParams = @{
                        Identity                   = $pfAlias
                        BatchName                  = $batchName
                        TargetDatabase             = $pfDb
                        PublicFolder               = $true
                        SuspendWhenReadyToComplete = $true
                        BadItemLimit               = $badItem
                        LargeItemLimit             = $largeItem
                        AcceptLargeDataLoss        = $acceptLDL
                        ErrorAction                = 'Stop'
                    }
                    New-MoveRequest @pfParams -WhatIf:([bool]($Mode -eq 'Simulate')) | Out-Null
                    Write-Log "  $batchName - PublicFolder $pfAlias -> $pfDb (via New-MoveRequest)" -Level Sub
                }
            }
    }

    # --- Final snapshot + HTML (Apply) ---------------------------------------
    # We use Get-MbSnapshot to get the batch-centric shape (see helper above).
    # The HTML now expects this shape (one PSCustomObject per MigrationBatch with Users[]).
    if ($Mode -eq 'Apply') {
        Start-Sleep -Seconds 3
        $final = Get-MbSnapshot

        # CSV: we flatten per user to keep a usable CSV format
        $csvRows = foreach ($b in $final) {
            foreach ($u in $b.Users) {
                [PSCustomObject]@{
                    Batch              = $b.Name
                    BatchStatus        = $b.Status
                    Identity           = $u.Identity
                    UserStatus         = $u.Status
                    PercentComplete    = $u.PercentageComplete
                    TargetDatabase     = $u.TargetDatabase
                    Error              = $u.Error
                    FailureType        = $u.FailureType
                    LastUpdate         = $u.LastUpdateTimestamp
                    SkippedItems       = $u.SkippedItemCount
                }
            }
        }
        $csvPath = Join-Path $OutputFolder 'MigrationStatus.csv'
        $csvRows | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8 -Delimiter ';'
        Add-Report -Step '20-Move' -Target 'GLOBAL' -Action 'Export-Csv (final)' `
                   -Status Success -AfterValue $csvPath

        $htmlPath = Join-Path $OutputFolder 'MigrationStatus.html'
        New-MigrationStatusHtml -Stats $final -OutputPath $htmlPath -ReportMode $Mode `
                                -Title 'Migration started - initial report'
        Write-Log "Migration HTML report: $htmlPath" -Level Success
        Add-Report -Step '20-Move' -Target 'GLOBAL' -Action 'Export-Html' `
                   -Status Success -AfterValue $htmlPath -Detail 'Initial report after submission'
    }

    Save-Report -StepName 'Step20-RunMigration' | Out-Null
    return 0
}
